### ISSUE TITLE
This package breaks android build with react-native 0.64.1 - FirebaseInstanceId seems to no longer be supported

### ISSUE THREAD

**Issue by goleary** [zo0r/react-native-push-notification#1981]
# Bug
When I run `yarn android` I get this error:
```
C:\Users\____\github\rnfPushRepro\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotification.java:39: error: cannot find symbol
import com.google.firebase.iid.FirebaseInstanceId;
symbol:   class FirebaseInstanceId
location: package com.google.firebase.iid
```
There are numerous of these errors.

It appears as though the issue is that [FirebaseInstanceId has been deprecated](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId) 

## Environment info
```bash
System:
    OS: Windows 10 10.0.19041
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 35.20 GB / 63.74 GB
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, 
android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: Not Found
  Languages:
    Java: 15.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 7.2.3

## Steps To Reproduce

1. `npx react-native init MyApp`
2. `cd MyApp`
3. `yarn add react-native-push-notification`
4. `yarn android`

## Reproducible sample code

example repro here: https://github.com/goleary/rnfPushRepro

**Comment by emrecanozkok** [comment]
Same error

**Comment by goleary** [comment]
All I had to do was update `android/build.gradle` to lock the version of `firebase-messaging`
```
ext {
        ...
        firebaseMessagingVersion = "21.1.0"
}
```

**Comment by mrtry** [comment]
Worked for me. 

in `android/build.gradle`
```
subprojects {
    afterEvaluate {project ->
        if (project.name == 'react-native-push-notification') {
            project.dependencies.add('implementation', 'com.google.firebase:firebase-iid:21.1.0')
        }
    }
}
```

**Comment by stefoid** [comment]
mrtry, can you explain that does?

I am having the same issue, but setting firebaseMessagingVersion to 21.1.0 in gradle file does not help.  I still see dependency 22.0.0 being pulled in.

I imagine it is because I have this in the gradle file which overrides?

    subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'com.google.android.gms'
                        && !details.requested.name.contains('multidex') ) {
                    details.useVersion "+"
                }

                **if (details.requested.group == 'com.google.firebase'
                        && !details.requested.name.contains('multidex') ) {
                    details.useVersion "+"**
                }
            }
        }

Im not sure why that is there exactly - maybe it is now useless, but I am inclined not remove things without reason.

help!

**Comment by akiladevinda** [comment]
@goleary  trick works for me. Cheers

**Comment by devinkg** [comment]
> All I had to do was update `android/build.gradle` to lock the version of `firebase-messaging`
> 
> ```
> ext {
>         ...
>         firebaseMessagingVersion = "21.1.0"
> }
> ```

This worked for me.

**Comment by 201724468** [comment]
> firebaseMessagingVersion = "21.1.0"

you saved my life bro

**Comment by Dallas62** [comment]
Duplicate of #1979
