### ISSUE TITLE
🔥When updating 3.4 to 3.5, unable to compile Android

### ISSUE THREAD

**Issue by wmonecke** [zo0r/react-native-push-notification#1449]
# Bug

When upgrading from 3.4 to 3.5 I am unable to compile on Android.

This is what I am getting: 
````
> Task :react-native-push-notification:compileReleaseJavaWithJavac FAILED
/Users/waltermonecke/Documents/Code/React-Native2/moodPixel/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java:9: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/waltermonecke/Documents/Code/React-Native2/moodPixel/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java:13: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/waltermonecke/Documents/Code/React-Native2/moodPixel/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java:35: error: cannot find symbol
    public RNReceivedMessageHandler(@NonNull FirebaseMessagingService service) {
                                     ^
  symbol:   class NonNull
  location: class RNReceivedMessageHandler
Note: /Users/waltermonecke/Documents/Code/React-Native2/moodPixel/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

````
## Environment info

````
"react-native": "0.60.4",
"react-native-push-notification": "^3.5.0",
````

**Comment by Eldavid** [comment]
The same situation arises in my application too.

**Comment by Dallas62** [comment]
Hi,
Didn't caught this tiny import, I just released `3.5.1` this should be fixed.

**Comment by wmonecke** [comment]
@Dallas62 thank you!! :)
