### ISSUE TITLE
data.getSubtitle error on iOS

### ISSUE THREAD

**Issue by asphyxiar** [zo0r/react-native-push-notification#2204]
Hello, iam having a trouble while clicking on the notification, when the app is in the background and it pops an error that says 
data.getSubtitle is not a function. Anyone got any suggestions? thanks

**Comment by KristineTrona** [comment]
@asphyxiar were you able to find a way to fix this? I got the same error after updating from version `5.0.1` to `7.4.0`. RN version`0.63.2` and `@react-native-community/push-notification-ios` `1.4.0`

It looks like it was introduced in https://github.com/zo0r/react-native-push-notification/commit/614b4517744ff7f6ed8a0a86ef5835c39559438a

**Comment by karl007253** [comment]
@asphyxiar, Updating the notification libraries fixed mine.

`@react-native-community/push-notification-ios (1.10.1)`
`react-native-push-notification (8.1.1)`

**Comment by dnvarun** [comment]
After updating to the above versions, I got the following email after trying to upload the build:
```
ITMS-90338: Non-public API usage - The app references non-public selectors in PlugIns/PossibleNotification.appex/PossibleNotification: authorizedScopes, createRequest, estimatedProgress, initWithFrame:configuration:, initWithURL:configuration:, initWithURL:entersReaderIfAvailable:, isMainFrame, isPassthrough, navigationType, newSocketQueueForConnectionFromAddress:onSocket:, onSuccess:, removeValuesForKeys:completion:, setColor:animated:, setHighlightsToday:, setNavigationDelegate:, setProcessPool:, setRequestedOperation:, setRequestedScopes:, socket:didAcceptNewSocket:, socket:didConnectToHost:port:, socket:didConnectToUrl:, socket:didReadData:withTag:, socket:didReadPartialDataOfLength:tag:, socket:didReceiveTrust:completionHandler:, socket:didWriteDataWithTag:, socket:didWritePartialDataOfLength:tag:, socket:shouldTimeoutReadWithTag:elapsed:bytesDone:, socket:shouldTimeoutWriteWithTag:elapsed:bytesDone:, socketDidCloseReadStream:, socketDidDisconnect:withError:, socketDidSecure:, targetFrame, userContentController, websiteDataStore,The app references non-public selectors in <app_name>: authorizedScopes, createRequest, estimatedProgress, initWithFrame:configuration:, initWithURL:configuration:, initWithURL:entersReaderIfAvailable:, isMainFrame, isPassthrough, navigationType, newSocketQueueForConnectionFromAddress:onSocket:, onSuccess:, removeValuesForKeys:completion:, setColor:animated:, setHighlightsToday:, setNavigationDelegate:, setProcessPool:, setRequestedOperation:, setRequestedScopes:, socket:didAcceptNewSocket:, socket:didConnectToHost:port:, socket:didConnectToUrl:, socket:didReadData:withTag:, socket:didReadPartialDataOfLength:tag:, socket:didReceiveTrust:completionHandler:, socket:didWriteDataWithTag:, socket:didWritePartialDataOfLength:tag:, socket:shouldTimeoutReadWithTag:elapsed:bytesDone:, socket:shouldTimeoutWriteWithTag:elapsed:bytesDone:, socketDidCloseReadStream:, socketDidDisconnect:withError:, socketDidSecure:, targetFrame, userContentController, websiteDataStore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
```

Is there any other way to fix this?
