### ISSUE TITLE
Could not compile Android after upgrading to 6.1.1

### ISSUE THREAD

**Issue by j0nd0n7** [zo0r/react-native-push-notification#1678]
# Bug
Could not compile Android after upgrading to 6.1.1
```
a/path//node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java:62: error: cannot find symbol
            Integer visibilty = remoteNotification.getVisibility();
                                                  ^
  symbol:   method getVisibility()
  location: variable remoteNotification of type Notification
a/path//node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java:78: error: cannot find symbol
            Integer priority = remoteNotification.getNotificationPriority();
                                                 ^
  symbol:   method getNotificationPriority()
  location: variable remoteNotification of type Notification
Note: a/path//node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-push-notification:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 48s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (a/path//node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (a/path//node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at then.result (a/path//node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12)
```

`react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 152.17 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 22, 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom_64, android-23 | Android TV Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
```

Library version: 6.1.1

## Steps To Reproduce

**Comment by Dallas62** [comment]
Hi @j0nd0n7 
Not sure what is happening, but you probably have a version lock on the firebase messaging dependency (gradle).
https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage.Notification#getNotificationPriority()
This method is available but I don't see any "Target version" in the firebase documentation.

**Comment by j0nd0n7** [comment]
I'm configuring this in build.grade:

```
    implementation 'com.google.firebase:firebase-messaging:20.2.4'
    implementation 'com.google.firebase:firebase-analytics:17.3.0'
```

Do you have any recommendation regarding config / version?

Is the com.google.firebase:firebase-messaging required?

**Comment by Dallas62** [comment]
This is the latest version you are using, this should be ok.

Can you share your `buildscript.ext` configuration ?

**Comment by a-koka** [comment]
@j0nd0n7 How did you fix this? I'm having the same issue.

**Comment by phuongpt** [comment]
same for me (RN 0.62), I can't figure out solution it unless downgrade back to 5.1.1.

**Comment by phuongpt** [comment]
updates: 
Old: 
```
        googlePlayServicesVersion = "16.1.0" // default: "+"
        googlePlayServicesIidVersion = "16.0.1"
        firebaseVersion = "17.3.0" // default: "+"
        firebaseMessagingVersion = "17.3.0" // default: "+"
```
Changed to
```
 googlePlayServicesVersion = "+" // default: "+"
 firebaseMessagingVersion = "+" // default: "+"
```
And it resolved issue on 6.1 .3
