### ISSUE TITLE
Crash app with 7.3.0

### ISSUE THREAD

**Issue by gitlabLibs** [zo0r/react-native-push-notification#1992]
The application does not build from 7.2.3, if it is updated to 7.3.0 the application is built, but it crashes when opened without errors

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification/issues/1979#issuecomment-839755772

**Comment by invm** [comment]
The fix is for those that have `implementation 'com.google.firebase:firebase-core:16.0.0'` in their `app/build.gradle`? I don't have that implementation and the app still crashes, when I comment out  `import PushNotification from 'react-native-push-notification';` the app does not crash. 

`"react-native-push-notification": "7.3.0"` 

What could be the issue?

**Comment by gitlabLibs** [comment]
thanks

**Comment by Dallas62** [comment]
@invm Please read the full comment link above

**Comment by invm** [comment]
Well you've said that you do not recommend downgrading if there is not reason, didn't try it, but it works.

**Comment by tastafur** [comment]
@Dallas62 those of firebase say that it would be good to lock the version https://github.com/invertase/react-native-firebase/issues/5293#issuecomment-839918527 in this part https://github.com/zo0r/react-native-push-notification/blob/7315f4362edea523d4abba69baad72f80801b391/android/build.gradle#L58

**Comment by salvoravida** [comment]
i got this error after upgrade to 7.3.0 on app startup

java.lang.ClassNotFoundException: com.google.firebase.iid.FirebaseInstanceId
    at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingModule.lambda$getToken$2(ReactNativeFirebaseMessagingModule.java:116)
    at io.invertase.firebase.messaging.-$$Lambda$ReactNativeFirebaseMessagingModule$Vj2oWQrpOl3AM5fw0hvH-cnu3p8.call
    at com.google.android.gms.tasks.zzv.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
    at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingModule.lambda$getToken$2(ReactNativeFirebaseMessagingModule.java:116)
    at io.invertase.firebase.messaging.-$$Lambda$ReactNativeFirebaseMessagingModule$Vj2oWQrpOl3AM5fw0hvH-cnu3p8.call
    at com.google.android.gms.tasks.zzv.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)

**Comment by Dallas62** [comment]
@salvoravida Read the thread, the answer is linked.

**Comment by mikehardy** [comment]
:wave: hi there - react-native-firebase maintainer here

Yes, a `+` in an internal dependency should not be done, breaking changes in your dependencies are breaking changes in the module. You need to track the dependency with an actual version number and release changes to it as you would breaking changes in your own module, so going from v21 to v22 of messaging should be a semver major here and carry the note that you bumped the SDK major underlying

There is still the escape valve / relief hatch of overriding it for those that need to, but then you are safely playing with the other firebase-consuming libraries in the ecosystem

**Comment by mikehardy** [comment]
related: version numbers are free, it could be 90 and no one minds, semver majors are not to be feared, but changelogs and defaulting-to-safety save developers so much time...

**Comment by nzrin** [comment]
No answers as stated in here https://github.com/zo0r/react-native-push-notification/issues/1979#issuecomment-839755772 solved my crash issue after upgrading to 7.3.0. 

Crash on app startup.

**Comment by Dallas62** [comment]
Hi @mikehardy this change will be consider to avoid this kind of breaking change in the future.

But there is still an issue when mixing various functionalities of the same ecosystem.
I understand that I can replace `+` by what I want, but we will be stuck in the same issue if I choose `22.0.0`.
The deprecation notice of `firebase-iid` was made 3 years ago. In the last 24 hours the API was removed.
Now this library is up to date after the failure and ready to run on v22.
Our chance was the crash appended at build time, which made the investigation easier for developers (no need to use logcat &Cie).
But for others library that use `firebase-iid`, such as `react-native-one-signal` and `react-native-firebase`, the crash is at runtime. And both libraries didn't take care of the deprecation notice (like this library before the fail).
A fix in respective repositories would be great and do not need to be on v22, v21 implement all necessary changes.

IMO, there is a real lack of functionalities in all (free) notification libraries.
In the past, `react-native-firebase` was handling local notifications, since it was removed everyone moved to this library.
In the same time, Android forced channels which made this library useless until v4.x.x.
This library is clearly not the best library if we take a look at functionalities and codebase. For now, I don't have time for now to refactor/change deeply this library, **maintainers are welcome** 😉.

To move forward, I will patch the current version of `firebase-messaging` to v21 to simplify the investigation of everyone but it's not because this library doesn't support v22 now.

What would be great to put in place in the react-native ecosystem, would be an Android-specific notification library. Such as the iOS one and without any notification provider (like firebase-messaging) since there is multiple way to do it in Android.
> If anyone is interested, feel free to contact me or create the project.

Actually developers can't use react-native-firebase without channel (default Firebase Channel is created in some rare cases).
They have 2 choices:
 - Create a Channel in their Apps in Java/Kotlin.
 - Use a library, like this one, which included unnecessary stuff for a channel.
So this Android-specific library could solve this kind of issues 🤞 

Regards,

PS: ℹ️ **If you are interested into maintain this project, contact me.**  ℹ️ 
Since I don't have rights to add a contributor/maintainer, it could take time to contact the owner.

**Comment by Dallas62** [comment]
@nzrin Can you provide a stacktrace with logcat ?

**Comment by nzrin** [comment]
This is my logcat while I tried to open my app before it crashed.

```java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
        at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingModule.lambda$getToken$2(ReactNativeFirebaseMessagingModule.java:111)
        at io.invertase.firebase.messaging.-$$Lambda$ReactNativeFirebaseMessagingModule$Vj2oWQrpOl3AM5fw0hvH-cnu3p8.call(Unknown Source:4)
        at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId"```

**Comment by mikehardy** [comment]
> In the last 24 hours the API was removed

"...in the last release of the library", that part is missing but critical from my point of view, and for my argument

There will always be incompatibilities, and forward progress, and delays in handling some deprecations while were are busy handling others, I'm just trying to persuade the *controlled* introduction of breaking change

No big refactors or anything, just controlled release of breaking change. If you do make that change (and I'd start with v21 of messaging for your v7.x release then do a v8 with v22 dependencies, personally) I think that will protect people in the future

Indeed, Notifee.app exists completely because the "local device notification" API space is extraordinarily difficult to cover since the API surface area is enormous and the API skews across mobile operating system version so much. Sadly, an open source model was not enough to fund the sustained effort required in react-native-firebase, thus Notifee.app. I'm not trying to sell anyone on a paid module, I'm just saying it's hard. A hard problem, and that was the path Invertase took.

For you @Dallas62 as a fellow module maintainer, I can only sympathize. It's clear you are hear because you're trying to help people and this whole thing today is not much fun. Everyone else reading here should take note and empathize in case you are feeling frustrated. It's not easy...

Cheers

**Comment by Dallas62** [comment]
> This is my logcat while I tried to open my app before it crashed.
> 
> `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId; at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingModule.lambda$getToken$2(ReactNativeFirebaseMessagingModule.java:111) at io.invertase.firebase.messaging.-$$Lambda$ReactNativeFirebaseMessagingModule$Vj2oWQrpOl3AM5fw0hvH-cnu3p8.call(Unknown Source:4) at com.google.android.gms.tasks.zzv.run(Unknown Source:2) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId"`

@nzrin You can install the version 7.3.1 which pin the version of `firebase-messaging` to `21.1.0`.

**Comment by nzrin** [comment]
Thank you @Dallas62 !!! Upgrading to version 7.3.1 fixed this issue!

**Comment by mswieboda** [comment]
`7.3.1` worked for me as well, without any crashes, thank you! Appreciate your time @Dallas62 !

**Comment by babyrusa** [comment]
Hi I updated to version 7.3.1 due to the same issue everyone was having
However I'm having some issues when starting up the app as well. It seems like it 's related to lodash (a dependency of some package I'm not sure. I don't have lodash in my project)
```
Unable to resolve module ....

None of these files exist:
  * node_modules\lodash\_baseTrim(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\lodash\_baseTrim\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | var isObject = require('./isObject'),
  2 |     isSymbol = require('./isSymbol');
  3 |
```

Does anyone know why?
```
    "@react-native-firebase/app": "^11.2.0",
    "@react-native-firebase/messaging": "^11.2.0",

    "react": "^17.0.1",
    "react-native": "^0.64.0",
    "react-native-push-notification": "^7.3.1",
```

**Comment by Dallas62** [comment]
Hi @babyrusa,
Lodash is not a dependency of this repository... probably another library was updated.

**Comment by babyrusa** [comment]
I know but it only happened right after I updated this library..which is weird. I've compared the package.json file but I didn't update anything else...which is here. Here to see if anyone has a similar issue....

**Comment by Dallas62** [comment]
@babyrusa did you compare the lock file ?

**Comment by gluons** [comment]
`7.3.1` solves the problem.

Thank you @mikehardy for your help.  
Thank you @Dallas62 for quick fix.

Take care. ♥

**Comment by mikehardy** [comment]
Just a quick note that react-native-firebase is using the current firebase SDK versions as of react-native-firebase v12 (just released this morning) so this dependency collision should not occur across these two related projects that share the underlying firebase SDKs. Thanks to @Dallas62 for the interim release here that pinned the version, and now we can hopefully all make forward progress for future versions. Cheers
